name: Docker Containers
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
permissions:
  contents: read
  packages: write
env:
  IMAGE: nialtoservices/postgres-backup
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        postgres_major:
          - '14'
          - '15'
          - '16'
          - '17'
          - '18'
        include:
          - alpine_version: '3.20'
            postgres_major: '14'
          - alpine_version: '3.22'
            postgres_major: '15'
          - alpine_version: '3.23'
            postgres_major: '16'
          - alpine_version: '3.23'
            postgres_major: '17'
          - alpine_version: '3.23'
            postgres_major: '18'
    steps:
      - name: Extract metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ env.IMAGE }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Authenticate with the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push by digest
        uses: docker/build-push-action@v6
        id: build
        with:
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ALPINE_VERSION=${{ matrix.alpine_version }}
            POSTGRES_MAJOR=${{ matrix.postgres_major }}
          outputs: |
            type=image,name=ghcr.io/${{ env.IMAGE }},name-canonical=true,push=true,push-by-digest=true
      - name: Prepare digest
        run: |
          PLATFORM="${{ matrix.platform }}"
          DIGEST="${{ steps.build.outputs.digest }}"
          echo "DIGEST_NAME=digests-${{ matrix.postgres_major }}-${PLATFORM//\//-}" >> $GITHUB_ENV
          mkdir -p /tmp/digests
          touch /tmp/digests/${DIGEST#sha256:}
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DIGEST_NAME }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1
  merge:
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        postgres_major:
          - '14'
          - '15'
          - '16'
          - '17'
          - '18'
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-${{ matrix.postgres_major }}-*
          merge-multiple: true
      - name: Extract metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ env.IMAGE }}
          tags: |
            type=semver,pattern=${{ matrix.postgres_major }}-{{major}}
            type=semver,pattern=${{ matrix.postgres_major }}-{{major}}.{{minor}}
            type=semver,pattern=${{ matrix.postgres_major }}-{{version}}
            type=raw,value=${{ matrix.postgres_major }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Authenticate with the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create \
            $(echo -n "$DOCKER_METADATA_OUTPUT_JSON" | jq -cr '.tags | map("-t " + .) | join(" ")') \
            $(printf 'ghcr.io/${{ env.IMAGE }}@sha256:%s ' *)
      - name: Inspect manifest list
        run: |
          docker buildx imagetools inspect \
            ghcr.io/${{ env.IMAGE }}:${{ matrix.postgres_major }}
